#!/bin/bash
# rebrand.sh - Automated OpenHand → OpenHand rebrand
# Generated by Bob for Eythos Foundation
# Date: 2026-03-03 00:04 EST

set -e

echo "🔥 Starting OpenHand rebrand..."
echo "📊 Scope: ~30,000 replacements"
echo ""

# Backup
BACKUP_TAG="pre-rebrand-backup-$(date +%s)"
git tag "$BACKUP_TAG"
echo "✅ Created backup tag: $BACKUP_TAG"
echo ""

# Phase 1: Replace "openhand" → "openhand" (lowercase)
echo "Phase 1: Replacing 'openhand' → 'openhand'..."
find . -type f \
  -not -path "*/node_modules/*" \
  -not -path "*/.git/*" \
  -not -path "*/dist/*" \
  -not -path "*/build/*" \
  -not -path "*/.next/*" \
  -not -path "*/coverage/*" \
  -not -path "*/rebrand.sh" \
  \( -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \
     -o -name "*.md" -o -name "*.json" -o -name "*.yml" -o -name "*.yaml" \
     -o -name "*.sh" -o -name "*.py" -o -name "*.go" -o -name "*.rs" \
     -o -name "*.toml" -o -name "*.txt" -o -name "*.html" -o -name "*.css" \
     -o -name "*.scss" -o -name "*.less" -o -name "*.vue" -o -name "*.svelte" \
     -o -name "Dockerfile" -o -name "Makefile" -o -name ".env*" \) \
  -exec sed -i '' 's/openhand/openhand/g' {} + 2>/dev/null || true

echo "✅ Phase 1 complete"
echo ""

# Phase 2: Replace "OpenHand" → "OpenHand" (PascalCase)
echo "Phase 2: Replacing 'OpenHand' → 'OpenHand'..."
find . -type f \
  -not -path "*/node_modules/*" \
  -not -path "*/.git/*" \
  -not -path "*/dist/*" \
  -not -path "*/build/*" \
  -not -path "*/.next/*" \
  -not -path "*/coverage/*" \
  -not -path "*/rebrand.sh" \
  \( -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \
     -o -name "*.md" -o -name "*.json" -o -name "*.yml" -o -name "*.yaml" \
     -o -name "*.sh" -o -name "*.py" -o -name "*.go" -o -name "*.rs" \
     -o -name "*.toml" -o -name "*.txt" -o -name "*.html" -o -name "*.css" \
     -o -name "*.scss" -o -name "*.less" -o -name "*.vue" -o -name "*.svelte" \
     -o -name "Dockerfile" -o -name "Makefile" -o -name ".env*" \) \
  -exec sed -i '' 's/OpenHand/OpenHand/g' {} + 2>/dev/null || true

echo "✅ Phase 2 complete"
echo ""

# Phase 3: Replace "OPENHAND" → "OPENHAND" (UPPERCASE)
echo "Phase 3: Replacing 'OPENHAND' → 'OPENHAND'..."
find . -type f \
  -not -path "*/node_modules/*" \
  -not -path "*/.git/*" \
  -not -path "*/dist/*" \
  -not -path "*/build/*" \
  -not -path "*/.next/*" \
  -not -path "*/coverage/*" \
  -not -path "*/rebrand.sh" \
  \( -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \
     -o -name "*.md" -o -name "*.json" -o -name "*.yml" -o -name "*.yaml" \
     -o -name "*.sh" -o -name "*.py" -o -name "*.go" -o -name "*.rs" \
     -o -name "*.toml" -o -name "*.txt" -o -name "*.html" -o -name "*.css" \
     -o -name "*.scss" -o -name "*.less" -o -name "*.vue" -o -name "*.svelte" \
     -o -name "Dockerfile" -o -name "Makefile" -o -name ".env*" \) \
  -exec sed -i '' 's/OPENHAND/OPENHAND/g' {} + 2>/dev/null || true

echo "✅ Phase 3 complete"
echo ""

# Phase 4: Update GitHub URLs
echo "Phase 4: Updating GitHub URLs..."
find . -type f \
  -not -path "*/node_modules/*" \
  -not -path "*/.git/*" \
  -not -path "*/dist/*" \
  -not -path "*/build/*" \
  -not -path "*/.next/*" \
  -not -path "*/coverage/*" \
  -not -path "*/rebrand.sh" \
  -exec sed -i '' 's|github\.com/openhand/openhand|github.com/Eythos-Foundation/OpenHand|g' {} + 2>/dev/null || true

echo "✅ Phase 4 complete"
echo ""

# Phase 5: Rename bin files
echo "Phase 5: Renaming binary files..."
if [ -f "bin/openhand" ]; then
  mv bin/openhand bin/openhand
  echo "  ✅ Renamed bin/openhand → bin/openhand"
fi
if [ -f "bin/openhand.js" ]; then
  mv bin/openhand.js bin/openhand.js
  echo "  ✅ Renamed bin/openhand.js → bin/openhand.js"
fi
if [ -f "bin/openhand.ts" ]; then
  mv bin/openhand.ts bin/openhand.ts
  echo "  ✅ Renamed bin/openhand.ts → bin/openhand.ts"
fi
echo "✅ Phase 5 complete"
echo ""

# Phase 6: Update package.json shebang references
echo "Phase 6: Updating bin references in package.json..."
if [ -f "package.json" ]; then
  sed -i '' 's|"bin/openhand|"bin/openhand|g' package.json
  echo "  ✅ Updated package.json bin paths"
fi
echo "✅ Phase 6 complete"
echo ""

echo "🎉 Rebrand complete!"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff"
echo "  2. Check for missed references: ./verify-rebrand.sh"
echo "  3. Test build: pnpm install && pnpm build"
echo "  4. Run tests: pnpm test"
echo "  5. Commit: git add -A && git commit -m 'Rebrand: OpenHand → OpenHand'"
echo ""
echo "💀 Bob"
