#!/bin/bash
# verify-rebrand.sh - Check for remaining OpenHand references
# Generated by Bob for Eythos Foundation
# Date: 2026-03-03 00:05 EST

echo "🔍 Scanning for remaining OpenHand references..."
echo ""

# Create output file
OUTPUT_FILE="rebrand-check.txt"
rm -f "$OUTPUT_FILE"

# Search for remaining references (excluding known false positives)
grep -ri "openhand\|OpenHand\|OPENHAND" . \
  --exclude-dir=node_modules \
  --exclude-dir=.git \
  --exclude-dir=dist \
  --exclude-dir=build \
  --exclude-dir=.next \
  --exclude-dir=coverage \
  --exclude="*.log" \
  --exclude="MIGRATION.md" \
  --exclude="OPENHAND-REBRAND-PLAN.md" \
  --exclude="rebrand.sh" \
  --exclude="verify-rebrand.sh" \
  --exclude="rebrand-check.txt" \
  2>/dev/null | grep -v "^Binary file" > "$OUTPUT_FILE" || true

# Count results
COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')

if [ "$COUNT" -gt 0 ]; then
  echo "⚠️  Found $COUNT references to review:"
  echo ""
  head -20 "$OUTPUT_FILE"
  if [ "$COUNT" -gt 20 ]; then
    echo ""
    echo "... and $((COUNT - 20)) more (see rebrand-check.txt for full list)"
  fi
  echo ""
  echo "Full report saved to: $OUTPUT_FILE"
  exit 1
else
  echo "✅ No OpenHand references found!"
  echo "🎉 Rebrand verification PASSED!"
  rm -f "$OUTPUT_FILE"
  exit 0
fi
