export const browserCoreExamples = [
  "openhand browser status",
  "openhand browser start",
  "openhand browser stop",
  "openhand browser tabs",
  "openhand browser open https://example.com",
  "openhand browser focus abcd1234",
  "openhand browser close abcd1234",
  "openhand browser screenshot",
  "openhand browser screenshot --full-page",
  "openhand browser screenshot --ref 12",
  "openhand browser snapshot",
  "openhand browser snapshot --format aria --limit 200",
  "openhand browser snapshot --efficient",
  "openhand browser snapshot --labels",
];

export const browserActionExamples = [
  "openhand browser navigate https://example.com",
  "openhand browser resize 1280 720",
  "openhand browser click 12 --double",
  'openhand browser type 23 "hello" --submit',
  "openhand browser press Enter",
  "openhand browser hover 44",
  "openhand browser drag 10 11",
  "openhand browser select 9 OptionA OptionB",
  "openhand browser upload /tmp/openhand/uploads/file.pdf",
  'openhand browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openhand browser dialog --accept",
  'openhand browser wait --text "Done"',
  "openhand browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openhand browser console --level error",
  "openhand browser pdf",
];
